// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxgqiyrltxwyasuogueu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54Z3FpeXJsdHh3eWFzdW9ndWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODM4MjQsImV4cCI6MjA1ODE1OTgyNH0.WbIc8F6kqb7hRgVZ4gRKrOFRy5ViWYqKesEsDba4E0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);